version: "2.3"
services:
    milvus:
        restart: always
        image: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
        volumes:
            - ./milvus.yaml:/var/lib/milvus/conf/milvus.yaml
        ports:
            - "0.0.0.0:19530:19530"
