version: "2.3"
services:
    milvus:
        restart: always
        image: milvusdb/milvus:0.11.0-cpu-d101620-4c44c0
        volumes:
            - ./milvus.yaml:/var/lib/milvus/conf/milvus.yaml
        ports:
            - "0.0.0.0:19530:19530"
