pull_request_rules:
  - name: Test passed
    conditions:
      - or:
        - base=master
        - base~=2\.\d
      - "status-success=Run Python Tests (3.8, windows-2022)"
      - "status-success=Run Python Tests (3.13, windows-2022)"
      - "status-success=Run Python Tests (3.8, ubuntu-22.04)"
      - "status-success=Run Python Tests (3.13, ubuntu-22.04)"
      - "status-success=Run Check Proto (3.8)"
      - "status-success=Code lint check (3.8)"
      - "status-success=Run Check Proto (3.13)"
      - "status-success=Code lint check (3.13)"
    actions:
      label:
        add:
          - ci-passed
  - name: Add needs-dco label when DCO check failed
    conditions:
      - or:
        - base=master
        - base~=2\.\d
      - -status-success=DCO
    actions:
      label:
        remove:
          - dco-passed
        add:
          - needs-dco

  - name: Add dco-passed label when DCO check passed
    conditions:
      - or:
        - base=master
        - base~=2\.\d
      - status-success=DCO
    actions:
      label:
        remove:
          - needs-dco
        add:
          - dco-passed

