# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: make-format
        name: Format code with black and ruff
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      
      - id: make-lint
        name: Lint code with black and ruff
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
