# Configuration File for CodeCov
coverage:
  precision: 2
  round: down
  range: "70...100"

  # status:
  #   project:
  #     default:
  #       target: 77%
  #       threshold: 0% #Allow the coverage to drop by threshold%, and posting a success status.
  #   patch:
  #     default:
  #       target: 80%   #target of patch diff
  #       threshold: 0%
  #       if_ci_failed: error #success, failure, error, ignore
