# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import milvus_pb2 as milvus__pb2
import status_pb2 as status__pb2


class MilvusServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTable = channel.unary_unary(
        '/milvus.grpc.MilvusService/CreateTable',
        request_serializer=milvus__pb2.TableSchema.SerializeToString,
        response_deserializer=status__pb2.Status.FromString,
        )
    self.HasTable = channel.unary_unary(
        '/milvus.grpc.MilvusService/HasTable',
        request_serializer=milvus__pb2.TableName.SerializeToString,
        response_deserializer=milvus__pb2.BoolReply.FromString,
        )
    self.DropTable = channel.unary_unary(
        '/milvus.grpc.MilvusService/DropTable',
        request_serializer=milvus__pb2.TableName.SerializeToString,
        response_deserializer=status__pb2.Status.FromString,
        )
    self.BuildIndex = channel.unary_unary(
        '/milvus.grpc.MilvusService/BuildIndex',
        request_serializer=milvus__pb2.TableName.SerializeToString,
        response_deserializer=status__pb2.Status.FromString,
        )
    self.InsertVector = channel.unary_unary(
        '/milvus.grpc.MilvusService/InsertVector',
        request_serializer=milvus__pb2.InsertInfos.SerializeToString,
        response_deserializer=milvus__pb2.VectorIds.FromString,
        )
    self.SearchVector = channel.unary_stream(
        '/milvus.grpc.MilvusService/SearchVector',
        request_serializer=milvus__pb2.SearchVectorInfos.SerializeToString,
        response_deserializer=milvus__pb2.TopKQueryResult.FromString,
        )
    self.SearchVectorInFiles = channel.unary_stream(
        '/milvus.grpc.MilvusService/SearchVectorInFiles',
        request_serializer=milvus__pb2.SearchVectorInFilesInfos.SerializeToString,
        response_deserializer=milvus__pb2.TopKQueryResult.FromString,
        )
    self.DescribeTable = channel.unary_unary(
        '/milvus.grpc.MilvusService/DescribeTable',
        request_serializer=milvus__pb2.TableName.SerializeToString,
        response_deserializer=milvus__pb2.TableSchema.FromString,
        )
    self.GetTableRowCount = channel.unary_unary(
        '/milvus.grpc.MilvusService/GetTableRowCount',
        request_serializer=milvus__pb2.TableName.SerializeToString,
        response_deserializer=milvus__pb2.TableRowCount.FromString,
        )
    self.ShowTables = channel.unary_stream(
        '/milvus.grpc.MilvusService/ShowTables',
        request_serializer=milvus__pb2.Command.SerializeToString,
        response_deserializer=milvus__pb2.TableName.FromString,
        )
    self.Ping = channel.unary_unary(
        '/milvus.grpc.MilvusService/Ping',
        request_serializer=milvus__pb2.Command.SerializeToString,
        response_deserializer=milvus__pb2.ServerStatus.FromString,
        )


class MilvusServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTable(self, request, context):
    """*
    @brief Create table method

    This method is used to create table

    @param param, use to provide table information to be created.

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasTable(self, request, context):
    """*
    @brief Test table existence method

    This method is used to test table existence.

    @param table_name, table name is going to be tested.

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DropTable(self, request, context):
    """*
    @brief Delete table method

    This method is used to delete table.

    @param table_name, table name is going to be deleted.

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BuildIndex(self, request, context):
    """*
    @brief Build index by table method

    This method is used to build index by table in sync mode.

    @param table_name, table is going to be built index.

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InsertVector(self, request, context):
    """*
    @brief Add vector array to table

    This method is used to add vector array to table.

    @param table_name, table_name is inserted.
    @param record_array, vector array is inserted.

    @return vector id array
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchVector(self, request, context):
    """*
    @brief Query vector

    This method is used to query vector in table.

    @param table_name, table_name is queried.
    @param query_record_array, all vector are going to be queried.
    @param query_range_array, optional ranges for conditional search. If not specified, search whole table
    @param topk, how many similarity vectors will be searched.

    @return query result array.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchVectorInFiles(self, request, context):
    """*
    @brief Internal use query interface

    This method is used to query vector in specified files.

    @param file_id_array, specified files id array, queried.
    @param query_record_array, all vector are going to be queried.
    @param query_range_array, optional ranges for conditional search. If not specified, search whole table
    @param topk, how many similarity vectors will be searched.

    @return query result array.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DescribeTable(self, request, context):
    """*
    @brief Get table schema

    This method is used to get table schema.

    @param table_name, target table name.

    @return table schema
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTableRowCount(self, request, context):
    """*
    @brief Get table schema

    This method is used to get table schema.

    @param table_name, target table name.

    @return table schema
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowTables(self, request, context):
    """*
    @brief List all tables in database

    This method is used to list all tables.


    @return table names.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    """*
    @brief Give the server status

    This method is used to give the server status.

    @return Server status.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MilvusServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTable': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTable,
          request_deserializer=milvus__pb2.TableSchema.FromString,
          response_serializer=status__pb2.Status.SerializeToString,
      ),
      'HasTable': grpc.unary_unary_rpc_method_handler(
          servicer.HasTable,
          request_deserializer=milvus__pb2.TableName.FromString,
          response_serializer=milvus__pb2.BoolReply.SerializeToString,
      ),
      'DropTable': grpc.unary_unary_rpc_method_handler(
          servicer.DropTable,
          request_deserializer=milvus__pb2.TableName.FromString,
          response_serializer=status__pb2.Status.SerializeToString,
      ),
      'BuildIndex': grpc.unary_unary_rpc_method_handler(
          servicer.BuildIndex,
          request_deserializer=milvus__pb2.TableName.FromString,
          response_serializer=status__pb2.Status.SerializeToString,
      ),
      'InsertVector': grpc.unary_unary_rpc_method_handler(
          servicer.InsertVector,
          request_deserializer=milvus__pb2.InsertInfos.FromString,
          response_serializer=milvus__pb2.VectorIds.SerializeToString,
      ),
      'SearchVector': grpc.unary_stream_rpc_method_handler(
          servicer.SearchVector,
          request_deserializer=milvus__pb2.SearchVectorInfos.FromString,
          response_serializer=milvus__pb2.TopKQueryResult.SerializeToString,
      ),
      'SearchVectorInFiles': grpc.unary_stream_rpc_method_handler(
          servicer.SearchVectorInFiles,
          request_deserializer=milvus__pb2.SearchVectorInFilesInfos.FromString,
          response_serializer=milvus__pb2.TopKQueryResult.SerializeToString,
      ),
      'DescribeTable': grpc.unary_unary_rpc_method_handler(
          servicer.DescribeTable,
          request_deserializer=milvus__pb2.TableName.FromString,
          response_serializer=milvus__pb2.TableSchema.SerializeToString,
      ),
      'GetTableRowCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetTableRowCount,
          request_deserializer=milvus__pb2.TableName.FromString,
          response_serializer=milvus__pb2.TableRowCount.SerializeToString,
      ),
      'ShowTables': grpc.unary_stream_rpc_method_handler(
          servicer.ShowTables,
          request_deserializer=milvus__pb2.Command.FromString,
          response_serializer=milvus__pb2.TableName.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=milvus__pb2.Command.FromString,
          response_serializer=milvus__pb2.ServerStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'milvus.grpc.MilvusService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
