# Copyright (C) 2019-2021 Zilliz. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.

# Re-export all constants from client/constants.py for backward compatibility
from pymilvus.client.constants import (
    BATCH_SIZE,
    CALC_DIST_BIN_VEC,
    CALC_DIST_BM25,
    CALC_DIST_COSINE,
    CALC_DIST_DIM,
    CALC_DIST_FLOAT_VEC,
    CALC_DIST_HAMMING,
    CALC_DIST_IDS,
    CALC_DIST_IP,
    CALC_DIST_JACCARD,
    CALC_DIST_L2,
    CALC_DIST_METRIC,
    CALC_DIST_SQRT,
    CALC_DIST_TANIMOTO,
    COLLECTION_ID,
    COMMON_TYPE_PARAMS,
    DEFAULT_MAX_HAMMING_DISTANCE,
    DEFAULT_MAX_JACCARD_DISTANCE,
    DEFAULT_MAX_L2_DISTANCE,
    DEFAULT_MAX_TANIMOTO_DISTANCE,
    DEFAULT_MIN_COSINE_DISTANCE,
    DEFAULT_MIN_IP_DISTANCE,
    DEFAULT_SEARCH_EXTENSION_RATE,
    DISTANCE,
    EF,
    FIELDS,
    GUARANTEE_TIMESTAMP,
    ID,
    INT64_MAX,
    IS_PRIMARY,
    ITERATOR_FIELD,
    ITERATOR_SESSION_CP_FILE,
    ITERATOR_SESSION_TS_FIELD,
    MAX_BATCH_SIZE,
    MAX_FILTERED_IDS_COUNT_ITERATION,
    MAX_TRY_TIME,
    METRIC_TYPE,
    MILVUS_LIMIT,
    OFFSET,
    PARAMS,
    RADIUS,
    RANGE_FILTER,
    REDUCE_STOP_FOR_BEST,
    TYPE,
    UNLIMITED,
    BM25_b,
    BM25_k1,
)

__all__ = [
    "BATCH_SIZE",
    "CALC_DIST_BIN_VEC",
    "CALC_DIST_BM25",
    "CALC_DIST_COSINE",
    "CALC_DIST_DIM",
    "CALC_DIST_FLOAT_VEC",
    "CALC_DIST_HAMMING",
    "CALC_DIST_IDS",
    "CALC_DIST_IP",
    "CALC_DIST_JACCARD",
    "CALC_DIST_L2",
    "CALC_DIST_METRIC",
    "CALC_DIST_SQRT",
    "CALC_DIST_TANIMOTO",
    "COLLECTION_ID",
    "COMMON_TYPE_PARAMS",
    "DEFAULT_MAX_HAMMING_DISTANCE",
    "DEFAULT_MAX_JACCARD_DISTANCE",
    "DEFAULT_MAX_L2_DISTANCE",
    "DEFAULT_MAX_TANIMOTO_DISTANCE",
    "DEFAULT_MIN_COSINE_DISTANCE",
    "DEFAULT_MIN_IP_DISTANCE",
    "DEFAULT_SEARCH_EXTENSION_RATE",
    "DISTANCE",
    "EF",
    "FIELDS",
    "GUARANTEE_TIMESTAMP",
    "ID",
    "INT64_MAX",
    "IS_PRIMARY",
    "ITERATOR_FIELD",
    "ITERATOR_SESSION_CP_FILE",
    "ITERATOR_SESSION_TS_FIELD",
    "MAX_BATCH_SIZE",
    "MAX_FILTERED_IDS_COUNT_ITERATION",
    "MAX_TRY_TIME",
    "METRIC_TYPE",
    "MILVUS_LIMIT",
    "OFFSET",
    "PARAMS",
    "RADIUS",
    "RANGE_FILTER",
    "REDUCE_STOP_FOR_BEST",
    "TYPE",
    "UNLIMITED",
    "BM25_b",
    "BM25_k1",
]
