name: Test on pull request

on:
  push:
    branches:
      - 3.0
  pull_request:
    branches:
      - 3.0

jobs:
  build:
    name: Run Python Tests
    strategy:
      matrix:
        python-version: [3.8, 3.14]
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Fetch tags
        run: |
          git fetch --prune --unshallow --tags

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.21"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dependencies
        run: |
          uv sync --group dev --frozen --python python

      - name: Run unit coverage and lite integration tests
        run: |
          make coverage
          make integration-lite

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.PYMILVUS_CODE_COV_TOKEN }}
